Dashboard/urls.py
from django.urls import path

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    Home, ProductListView, ProductCreateView, ProductDeleteView, ProductUpdateView,ProductDetailView,
    CategorieListView, CategorieDetailView, CategorieCreateView, CategorieDeleteView, 
    OrderListView , OrdersDeleteView, OrdersUpdateView,OrderDetailView,  
    CustomerListView, CustomerDetailView,CustomerDeleteView, CustomerUpdateView,
    ProfileView, ProfileUpdateView, ExportCsv,UploadCsv,
    
    )

from shop.views import render_pdf_view
app_name='dashboard'

urlpatterns = [
    path('', Home.as_view(), name='dash'),
    
    #path('pie-chart/', Pie_chart.as_view(), name='pie-chart'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),

    path('products/', ProductListView.as_view(), name='product-list'),

    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('product/<str:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<str:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('products/<str:pk>/update/', ProductUpdateView.as_view(), name='product-update'),

    path('categories/', CategorieListView.as_view(), name='categorie-list'),

    path('create-categorie/', CategorieCreateView.as_view(), name='categorie-create'),
    path('<int:pk>/categorie/delete/', CategorieDeleteView.as_view(), name='categorie-delete'),
    path('categorie/<str:pk>/', CategorieDetailView.as_view(), name='categorie-detail'),

    path('orders/', OrderListView.as_view(), name='order-list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),

    #path('order/create/', CreateOrder.as_view(), name='order-create'),
    path('order/<int:pk>/delete/', OrdersDeleteView.as_view(), name='order-delete'),
    path('order/<int:pk>/update/', OrdersUpdateView.as_view(), name='order-update'),


    path('customers/', CustomerListView.as_view(), name='customer-list'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/<str:pk>/delete/', CustomerDeleteView.as_view(), name='customer-delete'),
    path('customer/<str:pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),

    path('upload-csv/', UploadCsv.as_view(), name='upload-csv'),
    path('export-csv/', ExportCsv.as_view(), name='export-csv'),

    path('order/invoice/<int:pk>', render_pdf_view, name='order-invoice')

]

Django-CRM/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from account.views import SignUpView, LoginView
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('home/', include('account.urls', namespace='account')),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path('dashboard/', include('Dashboard.urls', namespace='dashboard')),
    path('shop/', include('shop.urls', namespace='shop')),

    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]


urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    CategorieCreateView,  ProductListView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView,
     CategorieDeleteView, CategorieListView, CartItemsView,add_to_cart, delete_from_cart,Shop_home,
    remove_from_cart, CartView, OrdersCreateView, OrdersDeleteView, OrdersDetailView, OrdersListView
    ,CreateOrder, CategorieDetailView, render_pdf_view, ProfileView, ProfileUpdateView
    )

app_name='shop'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('', Shop_home.as_view(), name='shop-home'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('product/<str:pk>/', ProductDetailView.as_view(), name='product-detail'),
    #path('products/create/', ProductCreateView.as_view(), name='product-create'),
    #path('products/<str:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    #path('products/<str:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    
    #categorie
    path('categories/', CategorieListView.as_view(), name='categorie-list'),
    path('categorie/<str:pk>/', CategorieDetailView.as_view(), name='categorie-detail'),
    #path('create-categorie/', CategorieCreateView.as_view(), name='categorie-create'),
    #path('<int:pk>/categorie/delete/', CategorieDeleteView.as_view(), name='categorie-delete'),

    # cart
    #path('cart/', CartItemsView.as_view(), name='cart'),
    path('cart/', CartView.as_view(), name='cart'),

    path('products/add-to-cart/<str:id>/', add_to_cart, name='add-to-cart'),
    path('cart/add-to-cart/<str:id>/', add_to_cart, name='add-to-cart'),
    path('cart/remove-from-cart/<str:id>/', remove_from_cart, name='remove-from-cart'),

    path('delete-from-cart/<str:id>/', delete_from_cart, name='delete-from-cart'),


    # orders
    path('order/', OrdersListView.as_view(), name='order-list'),
    path('order/<int:pk>/', OrdersDetailView.as_view(), name='order-detail'),
    path('order/create/', OrdersCreateView.as_view(), name='order-create'),
    path('order/<int:pk>/delete/', OrdersDeleteView.as_view(), name='order-delete'),
    #path('order/<int:pk>/update/', OrdersUpdateView.as_view(), name='order-update'),

    #order pdf invoice

    path('order/invoice/<int:pk>', render_pdf_view, name='order-invoice')

]

Dashboard/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete


from account.models import User
# Create your models here.

Dashboard/forms.py
from django import forms
from shop.models import Product, Order, Categorie, Orderitems
from account.models import Customer, Manager

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'product_image',
            'description',
            'categorie',
            'price',
        )


class CategorieModelForm(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = (
            'name',
        )


class OrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'is_confirmed',
        )

class CustomerModelForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=(
            '__all__'
        )
class CsvModelForm(forms.Form):    
    csv_file=forms.FileField()

Dashboard/templates/dash-categories/views.py
from multiprocessing import context
from urllib import request
from django.shortcuts import render
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from account.mixins import ManagerRequiredMixin, AdminRequiredMixin
from .models import   Customer, Manager, Csv
from django.contrib.auth import get_user_model
from .forms import ProductModelForm, CategorieModelForm, OrderModelForm, CsvModelForm, CustomerModelForm
from shop.models import Product, Order, Categorie, Orderitems
from account.models import UserProfile
from account.forms import ProfileModelForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse

import csv
#User=get_user_model()
# Create your views here.



class Home(ManagerRequiredMixin, generic.View):
    template_name='dashboard/dash-base.html'
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.count()
        products=Product.objects.count()
        orders=Order.objects.filter(is_confirmed=True).count()
        customers=Customer.objects.count()
        profile=UserProfile.objects.get(user=self.request.user)
        context = {
            'categories':categorie,
            'products':products,
            'orders':orders,
            'customers':customers,
            'profile':profile
        }
        return render(self.request, 'dashboard/dash-base.html', context)

class StatisticView(ManagerRequiredMixin, generic.View):
    template_name = "dash-products/home.html"
    
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.count()
        products=Product.objects.count()
        orders=Order.objects.count()
        context = {
            'categories':categorie,
            'products':products,
            'orders':orders
        }
        
        return render(self.request, 'dash-products/home.html', context)


class Pie_chart(ManagerRequiredMixin, generic.View):
    def get(self,request):
        labels = []
        data = []

        queryset = Product.objects.order_by('-price')
        for q in queryset:

            labels.append(q.name)
            data.append(int(q.price))

        return render(request, 'dashboard/pie_chart.html', {
            'labels': labels,
            'data': data,
        })

class ProductListView(ManagerRequiredMixin, generic.ListView):
    template_name = "dash-products/product-list.html"
    
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.all()
        products=Product.objects.all()
        context = {
            'categories':categorie,
            'products':products
        }
        return render(self.request, 'dash-products/product-list.html', context)

class ProductCreateView( ManagerRequiredMixin, generic.CreateView):
    template_name = "dash-products/product-create.html"
    form_class = ProductModelForm

    def get_success_url(self):
        messages.success(self.request, ' created successfully')
        return reverse("dashboard:product-list")
    
    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))
        



class ProductUpdateView(ManagerRequiredMixin, generic.UpdateView):
    template_name = "dash-products/product-update.html"
    form_class = ProductModelForm

    def get_queryset(self):
        return Product.objects.all()
    def get_success_url(self):
        messages.success(self.request, ' updated successfully')
        return reverse("dashboard:product-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))



class ProductDeleteView(ManagerRequiredMixin, generic.DeleteView):
    template_name = "dash-products/product-delete.html"
    def get_success_url(self):
        return reverse("dashboard:product-list")
    def get_queryset(self):
        return Product.objects.all()
        
    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
            messages.success(self.request, 'Product deleted successfully')
            return HttpResponseRedirect(success_url)
        except IntegrityError as e:
            messages.warning(self.request, "you can't remove product")
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieListView(LoginRequiredMixin, generic.ListView):
    template_name = "dash-categories/categorie-list.html"
    
    def get_queryset(self):
        return Categorie.objects.all()

    context_object_name='categories'

class CategorieCreateView(ManagerRequiredMixin, generic.CreateView):
    template_name = "dash-categories/categorie-create.html"
    form_class = CategorieModelForm

    

    def get_success_url(self):
        messages.success(self.request, 'Categorie created successfully')
        return reverse("dashboard:categorie-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieDeleteView(ManagerRequiredMixin, generic.DeleteView):
    template_name = "dash-categories/categorie-delete.html"
    
    def get_queryset(self):
        return Categorie.objects.all()

    def get_success_url(self):
        return reverse("dashboard:categorie-list")
    

    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
            messages.success(self.request, 'Categorie deleted successfully')
            return HttpResponseRedirect(success_url)
        except IntegrityError as e:
            messages.warning(self.request, "you can't remove categorie")
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieDetailView(ManagerRequiredMixin, generic.DetailView):
    template_name = "dash-categories/categorie-detail.html"
    
    def get(self, *args, **kwargs):
        categorie_id = self.kwargs['pk']
        categorie=Categorie.objects.get(id=categorie_id)
        items=Product.objects.filter(categorie=categorie)
        context = {
            'categorie':categorie,
            'items':items
        }
        return render(self.request, 'dash-categories/categorie-detail.html', context)

class OrderListView(ManagerRequiredMixin, generic.View):
    
    def get(self, *args, **kwargs):
        try:
            customer =Customer.objects.get(user=self.request.user)
            orders=Order.objects.all()

            context = {
                'orders': orders,
                'customer':customer
            }
            return render(self.request, 'dash-orders/order-list.html', context)
        except Exception :
            messages.warning(self.request, 'something went Wrong')



class CreateOrder(ManagerRequiredMixin,generic.View):
    def get(self, *args, **kwargs):
        try:
            cart=Cart.objects.get(user=self.request.user)
            items=CartItem.objects.filter(cart=cart)
            total_price=cart.get_cart_total
            context = {
                'items':items
            }
            order, created = Order.objects.get_or_create(
                    name=self.__str__() ,
                    user=self.request.user,
                    total_price=total_price
                )
            

            for item in items:
                Orderitems.objects.create(order=order,name=item.product.name ,product=item.product, price=item.get_total, quantity=item.quantity)
            order.save()

            return render(self.request,  'products/product-list.html', context)
        except Exception as e:
            messages.warning(self.request, 'something went Wrong')






class OrderDetailView(ManagerRequiredMixin, generic.DetailView):
    template_name = "dash-orders/order-detail.html"

    def get(self, *args, **kwargs):
        try:
            order_id = self.kwargs['pk']
            order=Order.objects.get(id=order_id)
            items=Orderitems.objects.filter(order=order)
            context = {
                'orders':order,
                'items':items
            }
            return render(self.request, 'dash-orders/order-detail.html', context)
        except Exception as e:
            messages.warning(self.request, 'something went Wrong')

    context_object_name='orders'
    


class OrdersUpdateView(ManagerRequiredMixin, generic.UpdateView):
    template_name = "dash-orders/order-update.html"
    form_class = OrderModelForm

    def get_queryset(self):
        return Order.objects.all()
    def get_success_url(self):
        messages.success(self.request, 'order updated successfully')
        return reverse("dashboard:order-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))

Dashboard/templates/dash-orders/order-delete.html
{% extends 'dashboard/dash-base.html' %}

{% block url %}<a href="{% url 'dashboard:categorie-create'%}"></a><br>{% endblock url %}
{% block type %}Orders {% endblock type %}
{% block title %}Orders {% endblock title %}
{% block active %}nav-link text-white{% endblock active %}
{% block order %}nav-link active{% endblock order %}
##########
{% block dash %}
        
    </form>
    
    <section class="h-100" >
        <div class="container h-100" style="width: 600px; margin-top: 100px;  border-radius: 15px; padding: 30px; background-color: rgb(245, 244, 244);">
        <form method="POST">

            <h4>are you sure want to delete this Order ?</h4><br><br>
            {% csrf_token %}
            {{form}}
            <button class="btn btn-danger">Yes, I am sure.</button>      
        </form>
        <a href="{% url 'dashboard:order-list'%}"> <button class="btn btn-primary">Back to Orders</button></a>    

        </div>
    </section>
{% endblock dash %}

Dashboard/templates/dash-orders/order-detail.html
{% extends 'dashboard/dash-base.html' %}
{% load static %}
{% block active %}nav-link text-white{% endblock active %}
{% block order %}nav-link active{% endblock order %}

{% block dash %}

<section class="h-100 h-custom" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card">
            <div class="card-body p-4">
  
              <div class="row">
  
                  <h5 class="mb-3"><a href="{% url 'dashboard:order-list'%}" class="text-body"><i
                        class="fas fa-long-arrow-alt-left me-2"></i>Back to Orders</a></h5>
                  <hr>
  
                  <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                      <p class="mb-1"><strong>Order name:</strong>   <span style="color: blue; ">{{orders.name}}</span></p> 
                      <p class="mb-0"> <strong>Price:</strong> {{orders.total_price}} $</p>
                    </div>
                  </div>
                  <div style="margin-bottom: 10px;">
                    <a href="{% url 'dashboard:order-invoice' orders.id  %}"><button class="btn btn-secondary">Show PDF</button></a>
                    <a href="{% url 'dashboard:order-update' orders.pk %}"><button class="btn btn-primary">Update</button></a>
                  </div>
  
  
                  {% for p in items %}
        
                    {% csrf_token %}
          
                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                          <div>
                            <img
                              src="{{ p.product.product_image.url}}"
                              class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                          </div>
                          <div class="ms-3">
                            <h5>{{p.name}}</h5>
                            <p class="small mb-0">{{p.product.description}}</p>
                          </div>
                        </div>
                        <div class="d-flex flex-row align-items-center">
                          <div style="width: 150px;">
                            <h5 class="quantity fw-normal mb-0">Quantity: {{p.quantity}}</h5>
                          </div>
                          

                          
                          
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                
                
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock dash %}

Dashboard/templates/dash-orders/order-list.html
{% extends 'dashboard/dash-base.html' %}
{% load static %}

{% block url %}<a href="{% url 'dashboard:order-list'%}"><br>{% endblock url %}
{% block type %}Orders {% endblock type %}
{% block title %}Orders {% endblock title %}
{% block active %}nav-link text-white{% endblock active %}
{% block order %}nav-link active{% endblock order %}

{% block dash %}


<section class="ml-5" style="margin: 30px;">
    <table class="table align-middle mb-0 bg-white" >
        <thead class="bg-light">
        <tr>
            <th>Order Name</th>
            <th>Confirmed</th>
            <th>Invoice</th>
            <th>Detail</th>
            <th>Delete</th>

        </tr>
        </thead>
        <tbody>
            {% for o in orders %}
                <tr>
            <td>
            <div class="d-flex align-items-center">
                <img
                    src="{{ o.user.more.image.url }}"
                    alt=""
                    style="width: 45px; height: 45px"
                    class="rounded-circle"
                    />
                <div class="ms-3">
                <p class="fw-bold mb-1">{{o.name}}</p>
                <p class="text-muted mb-0">john.doe@gmail.com</p>
                </div>
            </div>
            </td>
            {% if o.is_confirmed %}
            <td>
                <span class="badge rounded-pill bg-success">{{o.is_confirmed}}</span>
            </td>
            {% else %}
            <td>
                <span class="badge rounded-pill bg-warning">{{o.is_confirmed}}</span>
            </td>
            {% endif %}
            <td>
                <a href="{% url 'dashboard:order-invoice' o.id  %}">
                    <button type="button" class="btn btn-secondary btn-sm btn-rounded">
                        PDF
                    </button>
                </a>
            </td>
            <td>
            <a href="{% url 'dashboard:order-detail' o.pk %}">
            <button type="button" class="btn btn-primary btn-sm btn-rounded">
                view
            </button>
            </a>
            </td>
            <td>
                <a href="{% url 'dashboard:order-delete' o.pk %}">
                <button type="button" class="btn btn-danger btn-sm btn-rounded">
                    delete
                </button>
                </a>
                </td>
        </tr>
        {% endfor%}
        </tbody>
    </table>
  </section>




{% endblock dash %}



  <section class="text-gray-600 body-font overflow-hidden bg-red-100 ">
    <div class="max-w-7xl mx-auto">

        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <div class="p-4">
                <label for="table-search" class="sr-only">Search</label>
                <div class="relative mt-1">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                    clip-rule="evenodd"></path>
                            </svg>
                        </div>
                        <input type="text" id="table-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-80 pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for items">
                </div>
            </div>
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="p-4">
                                <div class="flex items-center">
                                    <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                    <label for="checkbox-all-search" class="sr-only">checkbox</label>
                                </div>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Order name
                            </th>
                            
                            <th scope="col" class="px-6 py-3">
                                Category
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Price
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
    
                    <tbody>
                        {% for o in orders %}
    
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="w-4 p-4">
                                <div class="flex items-center">
                                    <input id="checkbox-table-search-1" type="checkbox" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                    <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
                                </div>
                            </td>
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                {{o.name}}
                            </th>
                            
                            <td class="px-6 py-4">
                                Laptop
                            </td>
                            <td class="px-6 py-4">
                                $ {{o.total_price}}
                            </td>
                            <td class="px-6 py-4 text-right">
                                <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
    
                    </tbody>
    
                </table>
            </div>
    
    </div>
        
</section>

<!-- component -->
<!-- This is an example component -->

Dashboard/templates/dash-orders/order-update.html
{% extends 'dashboard/dash-base.html' %}

{% block active %}nav-link text-white{% endblock active %}
{% block order %}nav-link active{% endblock order %}
{% block dash %}
<section class="h-100" >
    <div class="container h-100" style="width: 600px; margin-top: 100px;  border-radius: 15px; padding: 30px; background-color: rgb(245, 244, 244);">
        <h1>Confirm Order</h1>
        <form method="POST">
             <br>
            {% csrf_token %}
            {{form}} <br><br>
            <button style="margin-left:10px;" class="btn btn-danger"> confirm </button>
        </form>
    </div>
</section>

{% endblock dash %}