Dashboard/urls.py
from django.urls import path

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    Home, ProductListView, ProductCreateView, ProductDeleteView, ProductUpdateView,ProductDetailView,
    CategorieListView, CategorieDetailView, CategorieCreateView, CategorieDeleteView, 
    OrderListView , OrdersDeleteView, OrdersUpdateView,OrderDetailView,  
    CustomerListView, CustomerDetailView,CustomerDeleteView, CustomerUpdateView,
    ProfileView, ProfileUpdateView, ExportCsv,UploadCsv,
    
    )

from shop.views import render_pdf_view
app_name='dashboard'

urlpatterns = [
    path('', Home.as_view(), name='dash'),
    
    #path('pie-chart/', Pie_chart.as_view(), name='pie-chart'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),

    path('products/', ProductListView.as_view(), name='product-list'),

    path('products/create/', ProductCreateView.as_view(), name='product-create'),
    path('product/<str:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<str:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('products/<str:pk>/update/', ProductUpdateView.as_view(), name='product-update'),

    path('categories/', CategorieListView.as_view(), name='categorie-list'),

    path('create-categorie/', CategorieCreateView.as_view(), name='categorie-create'),
    path('<int:pk>/categorie/delete/', CategorieDeleteView.as_view(), name='categorie-delete'),
    path('categorie/<str:pk>/', CategorieDetailView.as_view(), name='categorie-detail'),

    path('orders/', OrderListView.as_view(), name='order-list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),

    #path('order/create/', CreateOrder.as_view(), name='order-create'),
    path('order/<int:pk>/delete/', OrdersDeleteView.as_view(), name='order-delete'),
    path('order/<int:pk>/update/', OrdersUpdateView.as_view(), name='order-update'),


    path('customers/', CustomerListView.as_view(), name='customer-list'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/<str:pk>/delete/', CustomerDeleteView.as_view(), name='customer-delete'),
    path('customer/<str:pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),

    path('upload-csv/', UploadCsv.as_view(), name='upload-csv'),
    path('export-csv/', ExportCsv.as_view(), name='export-csv'),

    path('order/invoice/<int:pk>', render_pdf_view, name='order-invoice')

]

Django-CRM/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from account.views import SignUpView, LoginView
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('home/', include('account.urls', namespace='account')),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path('dashboard/', include('Dashboard.urls', namespace='dashboard')),
    path('shop/', include('shop.urls', namespace='shop')),

    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]


urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    CategorieCreateView,  ProductListView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView,
     CategorieDeleteView, CategorieListView, CartItemsView,add_to_cart, delete_from_cart,Shop_home,
    remove_from_cart, CartView, OrdersCreateView, OrdersDeleteView, OrdersDetailView, OrdersListView
    ,CreateOrder, CategorieDetailView, render_pdf_view, ProfileView, ProfileUpdateView
    )

app_name='shop'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('', Shop_home.as_view(), name='shop-home'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('product/<str:pk>/', ProductDetailView.as_view(), name='product-detail'),
    #path('products/create/', ProductCreateView.as_view(), name='product-create'),
    #path('products/<str:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    #path('products/<str:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    
    #categorie
    path('categories/', CategorieListView.as_view(), name='categorie-list'),
    path('categorie/<str:pk>/', CategorieDetailView.as_view(), name='categorie-detail'),
    #path('create-categorie/', CategorieCreateView.as_view(), name='categorie-create'),
    #path('<int:pk>/categorie/delete/', CategorieDeleteView.as_view(), name='categorie-delete'),

    # cart
    #path('cart/', CartItemsView.as_view(), name='cart'),
    path('cart/', CartView.as_view(), name='cart'),

    path('products/add-to-cart/<str:id>/', add_to_cart, name='add-to-cart'),
    path('cart/add-to-cart/<str:id>/', add_to_cart, name='add-to-cart'),
    path('cart/remove-from-cart/<str:id>/', remove_from_cart, name='remove-from-cart'),

    path('delete-from-cart/<str:id>/', delete_from_cart, name='delete-from-cart'),


    # orders
    path('order/', OrdersListView.as_view(), name='order-list'),
    path('order/<int:pk>/', OrdersDetailView.as_view(), name='order-detail'),
    path('order/create/', OrdersCreateView.as_view(), name='order-create'),
    path('order/<int:pk>/delete/', OrdersDeleteView.as_view(), name='order-delete'),
    #path('order/<int:pk>/update/', OrdersUpdateView.as_view(), name='order-update'),

    #order pdf invoice

    path('order/invoice/<int:pk>', render_pdf_view, name='order-invoice')

]

Dashboard/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete


from account.models import User
# Create your models here.

Dashboard/forms.py
from django import forms
from shop.models import Product, Order, Categorie, Orderitems
from account.models import Customer, Manager

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'product_image',
            'description',
            'categorie',
            'price',
        )


class CategorieModelForm(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = (
            'name',
        )


class OrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'is_confirmed',
        )

class CustomerModelForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=(
            '__all__'
        )
class CsvModelForm(forms.Form):    
    csv_file=forms.FileField()

Dashboard/templates/dash-categories/views.py
from multiprocessing import context
from urllib import request
from django.shortcuts import render
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from account.mixins import ManagerRequiredMixin, AdminRequiredMixin
from .models import   Customer, Manager, Csv
from django.contrib.auth import get_user_model
from .forms import ProductModelForm, CategorieModelForm, OrderModelForm, CsvModelForm, CustomerModelForm
from shop.models import Product, Order, Categorie, Orderitems
from account.models import UserProfile
from account.forms import ProfileModelForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse

import csv
#User=get_user_model()
# Create your views here.



class Home(ManagerRequiredMixin, generic.View):
    template_name='dashboard/dash-base.html'
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.count()
        products=Product.objects.count()
        orders=Order.objects.filter(is_confirmed=True).count()
        customers=Customer.objects.count()
        profile=UserProfile.objects.get(user=self.request.user)
        context = {
            'categories':categorie,
            'products':products,
            'orders':orders,
            'customers':customers,
            'profile':profile
        }
        return render(self.request, 'dashboard/dash-base.html', context)

class StatisticView(ManagerRequiredMixin, generic.View):
    template_name = "dash-products/home.html"
    
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.count()
        products=Product.objects.count()
        orders=Order.objects.count()
        context = {
            'categories':categorie,
            'products':products,
            'orders':orders
        }
        
        return render(self.request, 'dash-products/home.html', context)


class Pie_chart(ManagerRequiredMixin, generic.View):
    def get(self,request):
        labels = []
        data = []

        queryset = Product.objects.order_by('-price')
        for q in queryset:

            labels.append(q.name)
            data.append(int(q.price))

        return render(request, 'dashboard/pie_chart.html', {
            'labels': labels,
            'data': data,
        })

class ProductListView(ManagerRequiredMixin, generic.ListView):
    template_name = "dash-products/product-list.html"
    
    def get(self, *args, **kwargs):
        categorie=Categorie.objects.all()
        products=Product.objects.all()
        context = {
            'categories':categorie,
            'products':products
        }
        return render(self.request, 'dash-products/product-list.html', context)

class ProductCreateView( ManagerRequiredMixin, generic.CreateView):
    template_name = "dash-products/product-create.html"
    form_class = ProductModelForm

    def get_success_url(self):
        messages.success(self.request, ' created successfully')
        return reverse("dashboard:product-list")
    
    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))
        



class ProductUpdateView(ManagerRequiredMixin, generic.UpdateView):
    template_name = "dash-products/product-update.html"
    form_class = ProductModelForm

    def get_queryset(self):
        return Product.objects.all()
    def get_success_url(self):
        messages.success(self.request, ' updated successfully')
        return reverse("dashboard:product-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))



class ProductDeleteView(ManagerRequiredMixin, generic.DeleteView):
    template_name = "dash-products/product-delete.html"
    def get_success_url(self):
        return reverse("dashboard:product-list")
    def get_queryset(self):
        return Product.objects.all()
        
    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
            messages.success(self.request, 'Product deleted successfully')
            return HttpResponseRedirect(success_url)
        except IntegrityError as e:
            messages.warning(self.request, "you can't remove product")
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieListView(LoginRequiredMixin, generic.ListView):
    template_name = "dash-categories/categorie-list.html"
    
    def get_queryset(self):
        return Categorie.objects.all()

    context_object_name='categories'

class CategorieCreateView(ManagerRequiredMixin, generic.CreateView):
    template_name = "dash-categories/categorie-create.html"
    form_class = CategorieModelForm

    

    def get_success_url(self):
        messages.success(self.request, 'Categorie created successfully')
        return reverse("dashboard:categorie-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieDeleteView(ManagerRequiredMixin, generic.DeleteView):
    template_name = "dash-categories/categorie-delete.html"
    
    def get_queryset(self):
        return Categorie.objects.all()

    def get_success_url(self):
        return reverse("dashboard:categorie-list")
    

    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
            messages.success(self.request, 'Categorie deleted successfully')
            return HttpResponseRedirect(success_url)
        except IntegrityError as e:
            messages.warning(self.request, "you can't remove categorie")
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))


class CategorieDetailView(ManagerRequiredMixin, generic.DetailView):
    template_name = "dash-categories/categorie-detail.html"
    
    def get(self, *args, **kwargs):
        categorie_id = self.kwargs['pk']
        categorie=Categorie.objects.get(id=categorie_id)
        items=Product.objects.filter(categorie=categorie)
        context = {
            'categorie':categorie,
            'items':items
        }
        return render(self.request, 'dash-categories/categorie-detail.html', context)

class OrderListView(ManagerRequiredMixin, generic.View):
    
    def get(self, *args, **kwargs):
        try:
            customer =Customer.objects.get(user=self.request.user)
            orders=Order.objects.all()

            context = {
                'orders': orders,
                'customer':customer
            }
            return render(self.request, 'dash-orders/order-list.html', context)
        except Exception :
            messages.warning(self.request, 'something went Wrong')



class CreateOrder(ManagerRequiredMixin,generic.View):
    def get(self, *args, **kwargs):
        try:
            cart=Cart.objects.get(user=self.request.user)
            items=CartItem.objects.filter(cart=cart)
            total_price=cart.get_cart_total
            context = {
                'items':items
            }
            order, created = Order.objects.get_or_create(
                    name=self.__str__() ,
                    user=self.request.user,
                    total_price=total_price
                )
            

            for item in items:
                Orderitems.objects.create(order=order,name=item.product.name ,product=item.product, price=item.get_total, quantity=item.quantity)
            order.save()

            return render(self.request,  'products/product-list.html', context)
        except Exception as e:
            messages.warning(self.request, 'something went Wrong')






class OrderDetailView(ManagerRequiredMixin, generic.DetailView):
    template_name = "dash-orders/order-detail.html"

    def get(self, *args, **kwargs):
        try:
            order_id = self.kwargs['pk']
            order=Order.objects.get(id=order_id)
            items=Orderitems.objects.filter(order=order)
            context = {
                'orders':order,
                'items':items
            }
            return render(self.request, 'dash-orders/order-detail.html', context)
        except Exception as e:
            messages.warning(self.request, 'something went Wrong')

    context_object_name='orders'
    


class OrdersUpdateView(ManagerRequiredMixin, generic.UpdateView):
    template_name = "dash-orders/order-update.html"
    form_class = OrderModelForm

    def get_queryset(self):
        return Order.objects.all()
    def get_success_url(self):
        messages.success(self.request, 'order updated successfully')
        return reverse("dashboard:order-list")

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.warning(self.request, 'something went Wrong')
        return self.render_to_response(self.get_context_data(form=form))

Dashboard/templates/dashboard/dash-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}  </title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
        body{
            background-color:#eee;
        }

        .nav-link:hover{
            background-color:#525252 !important;
        }

        .nav-link .fa{
            transition:all 1s;
        }

        .nav-link:hover .fa{
            transform:rotate(360deg);
        }
</style>
<body>
    <div class="d-flex flex-column vh-100 flex-shrink-0 p-3 text-white bg-dark" style="width: 250px; position: fixed;"> 
        <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none" > 
            <svg class="bi me-2" width="40" height="32"> </svg> 
            <span class="fs-4" style="margin-bottom: 30px; margin-top: 15px;">Dashboard</span> 
        </a> <hr>
         <ul class="nav nav-pills flex-column mb-auto"> 
             <li class="nav-item" style="margin-bottom: 25px;"> <a href="{% url 'dashboard:dash' %}" class="{% block active %}nav-link active{% endblock active %}" aria-current="page">
                  <i class="fa fa-home"></i><span class="ms-2">Home</span> </a> 
                </li> 
             <li style="margin-bottom: 25px;"> <a href="{% url 'dashboard:product-list' %}" class="{% block product %}nav-link text-white{% endblock product %}"> <i class="fa fa-first-order"></i><span class="ms-2">Producs</span> </a> </li> 
             <li style="margin-bottom: 25px;"> <a href="{% url 'dashboard:categorie-list' %}" class="{% block categorie %}nav-link text-white{% endblock categorie %}"> <i class="fa fa-cog"></i><span class="ms-2">Categories</span> </a> </li> 
             <li style="margin-bottom: 25px;"> <a href="{% url 'dashboard:order-list' %}" class="{% block order %}nav-link text-white{% endblock order %}"> <i class="fa fa-bookmark"></i><span class="ms-2">Orders</span> </a> </li> 
             {% if request.user.is_staff %}
             <li style="margin-bottom: 25px;"> <a href="{% url 'dashboard:customer-list' %}" class="{% block customer %}nav-link text-white{% endblock customer %}"> <i class="fa fa-bookmark"></i><span class="ms-2">Cutomers</span> </a> </li> 
            {% endif %}
         </ul> <hr> 
         <div class="dropdown"> 
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false"> 
                <img src="{{ user.more.image.url }}" alt="" width="32" height="32" class="rounded-circle me-2"> <strong>  {{user.username}}</strong>
            </a>
         <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1"> 
            <li><a class="dropdown-item" href="{% url 'dashboard:profile' %}">Profile</a></li> <li> <hr class="dropdown-divider"> </li> 
            <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li> 
         </ul> 
      </div>
      </div>
      <div style=" margin-left: 260px; height: 100%;">

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block type %} {% endblock type %}</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group me-2">
                {% block url %} {% endblock url %}
              </div>
            </div>
        </div>
        
          
        {% include 'messages.html' %}
        {% block dash %}
        <div class="row row-cols-1  row-cols-md-3 g-4" style="margin-left: 10px;">
        
                  
            <div class="col" style="border-radius: 50px;">
              <div class="card h-100 " style="width: 25em;">
                <div class="card-body">
                  <h1 class="card-title">Confirmed Orders</h5>
                    <hr>
                  <h3 class="card-text">{{orders}}</h3>
          
                  <a href="{% url 'dashboard:order-list'%}"><button class="btn btn-primary">view</button></a>
                  
                </div>
              </div>
            </div>
            <div class="col" style="border-radius: 50px;">
                <div class="card h-100 " style="width: 25em;">
                  <div class="card-body">
                    <h1 class="card-title">Total Categories</h5>
                      <hr>
                    <h3 class="card-text">{{categories}}</h3>
            
                    <a href="#"><button class="btn btn-primary">view</button></a>
                    
                  </div>
                </div>
              </div>
              <div class="col" style="border-radius: 50px;">
                <div class="card h-100 " style="width: 25em;">
                  <div class="card-body">
                    <h1 class="card-title">Total Products</h5>
                      <hr>
                    <h3 class="card-text">{{products}}</h3>
            
                    <a href="#"><button class="btn btn-primary">view</button></a>
                    
                  </div>
                </div>
              </div>
        
              <div class="col" style="border-radius: 50px;">
                <div class="card h-100 " style="width: 25em;">
                  <div class="card-body">
                    <h1 class="card-title">Total Customers</h5>
                      <hr>
                    <h3 class="card-text">{{customers}}</h3>
            
                    <a href="#"><button class="btn btn-primary">view</button></a>
                    
                  </div>
                </div>
              </div>
          
          </div>

          <style type="text/css">
            .why_ .box {
             text-align: center;
             margin-top: 45px;
             padding: 20px 100px;
             border-radius: 5px;
             background-color: #ffffff;
          }
          </style>
                <div class="row" style="margin: 10px;">
                  <div class="col-lg-6">
                      <div class="card">
                          <div class="card-body">
               
                              <h4 class="card-title mb-4">Line Chart</h4>

                              <!--
                              <div class="row text-center">
                                  <div class="col-4">
                                      <h5 class="mb-0">86541</h5>
                                      <p class="text-muted text-truncate">Activated</p>
                                  </div>
                                  <div class="col-4">
                                      <h5 class="mb-0">2541</h5>
                                      <p class="text-muted text-truncate">Pending</p>
                                  </div>
                                  <div class="col-4">
                                      <h5 class="mb-0">102030</h5>
                                      <p class="text-muted text-truncate">Deactivated</p>
                                  </div>
                              </div>
               -->
                              <canvas id="pie"></canvas>
               
                          </div>
                      </div>
                  </div> <!-- end col -->
               
                  <div class="col-lg-6">
                      <div class="card">
                          <div class="card-body">
               
                              <h4 class="card-title mb-4">Bar Chart</h4>
               
                              
               
                              <canvas id="bar-chart"></canvas>
               
                          </div>
                      </div>
                  </div> <!-- end col -->
               </div> <!-- end row -->
          
          
            <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
            <script>
          
          //pie chart
          
          var barColors = [
            "#b91d47",
            "#00aba9",
            "#2b5797",
            "#e8c3b9",
            "#1e7145"
          ];
          
          new Chart("pie", {
            type: "pie",
            data: {
              labels: {{ labels|safe }},
              datasets: [{
                backgroundColor: barColors,
                data: {{ data|safe }},
              }]
            },
            options: {
              title: {
                display: true,
                text: "Products Price"
              }
            }
          });
          
          // bar chart
          var xValues = ["Italy", "France", "Spain", "USA", "Argentina"];
          var yValues = [55, 49, 44, 24, 15];
          var barColors = ["red", "green","blue","orange","brown"];

          new Chart("bar-chart", {
            type: "bar",
            data: {
              labels: {{ labels_2|safe }},
              datasets: [{
                backgroundColor: barColors,
                data: {{ data_2|safe }},
              }]
            },
            options: {
              legend: {display: false},
              title: {
                display: true,
                text: "Orders by Total price"
              }
            }
          });
            </script>
        {% endblock dash %}
      </div>
      



</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
</html>



</html>

Dashboard/templates/dashboard/profile.html
{% extends 'dashboard/dash-base.html'%}

{% load static %}

{% block dash %}
<div class="row gutters-sm">
    <div class="col-md-4 mb-3">
      <div class="card">
        <div class="card-body">
          <div class="d-flex flex-column align-items-center text-center">
            <img src="{{ profile.image.url }}" alt="Admin" class="rounded-circle" width="150">
            <div class="mt-3">
              <h4>{{profile.name}}</h4>
              <p class="text-secondary mb-1">Full Stack Developer</p>
              <p class="text-muted font-size-sm">{{profile.adresse}}</p>
              <button class="btn btn-outline-primary">Message</button>
            </div>
          </div>
        </div>
      </div>
      
    </div>
    <div class="col-md-8">
      <div class="card mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">First Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.first_name}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Last Name</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.last_name}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Email</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.email}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Phone</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.phone_number}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Mobile</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.phone_number}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <h6 class="mb-0">Address</h6>
            </div>
            <div class="col-sm-9 text-secondary">
              {{profile.adresse}}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-12">
              <a class="btn btn-info " target="__blank" href="{% url 'dashboard:profile-update' user.userprofile.pk%}">Edit</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock dash %}

<div id="main-content" class="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
    sss
    {{user.username}}
    {{userprofile.name}}
    
    {{userprofile.age}}
    {{userprofile.email}}
    <img src="{{ userprofile.image.url }}">
    
    <a href="{% url 'Dashboard:profile-update' user.userprofile.pk%}"> update</a>
    
    
    <br>
    
    </div>

Dashboard/templates/dashboard/upload_csv.html
{% extends 'dashboard/dash-base.html' %}

{% block dash %}

<form action="{% url "dashboard:upload-csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
        <div class="col-md-8">
            <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        </div>                    
    </div>
    <br>
    <div class="form-group">                    
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
             <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
        </div> 
    </div>
</form>

{% endblock dash %}